spring:
  h2:
    console:
      enabled: true
      path: /h2
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver