INSERT INTO TB_SETOR(COD_SETOR, NOME) VALUES (1, 'Tecnologia');
INSERT INTO TB_FUNCIONARIOS(COD_FUNCIONARIO, EMAIL, NOME, ID_SETOR) VALUES (1, 'ADEILTON@GMAIL.COM', 'ADEILTON', 1);
INSERT INTO TB_PROBLEMAS(cod_Problema, nome, descricao) VALUES (1, 'TONER', 'USADO PARA TONER');
INSERT INTO TB_PROBLEMAS(cod_Problema, nome, descricao) VALUES (2, 'CILINDRO', 'USADO PARA CILINDRO');
INSERT INTO TB_PROBLEMAS(cod_Problema, nome, descricao) VALUES (3, 'OUTRO', 'USAR O CHAT PARA INFORMAR A SITUAÇÃO');
 

INSERT INTO TB_sec_USERS (ID, ACCOUNT_NON_EXPIRED, ACCOUNT_NON_LOCKED, CREDENTIALS_NON_EXPIRED, ENABLED, FULL_NAME, PASSWORD, USER_NAME, ID_FUNCIONARIO) VALUES (1, TRUE, TRUE, TRUE, TRUE, 'adeilton santana', '$2a$10$HFyZ2ewFs62eIG65ydOq3.qUH1EtlN58QWC63d.aQJcLW9iMh8C7.', 'ls', 1)