INSERT INTO TB_SETOR(COD_SETOR, NOME) VALUES (1, 'Tecnologia');
INSERT INTO TB_FUNCIONARIOS(COD_FUNCIONARIO, EMAIL, NOME, ID_SETOR) VALUES (1, 'ADEILTON@GMAIL.COM', 'ADEILTON', 1);
INSERT INTO TB_PROBLEMAS(cod_Problema, nome, descricao) VALUES (1, 'TONER', 'USADO PARA TONER');
INSERT INTO TB_TICKET(COD_TICKET, ASSUNTO, ATIVO, ID_FUNCIONARIO, ID_PROBLEMA) VALUES (1, 'TONER', true, 1, 1);




